name: Deploy website to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: MMAdvogados
        run: npm ci

      - name: Build
        working-directory: MMAdvogados
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add host
        run: ssh-keyscan -H 161.97.159.142 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync -avz --delete MMAdvogados/dist/ root@161.97.159.142:/var/www/mmadvogados/